name: auval On GitHub Actions
on: push

jobs:
  reproduce-problem:
    name: Reproduce auval Problem on macOS
    runs-on: macOS-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          clean: true
      - name: Go to Repository
        run: cd $GITHUB_WORKSPACE
      - name: Copy Audio Unit to Components Directory
        run: ditto ./ExamplePlugin.component ~/Library/Audio/Plug-Ins/Components/ExamplePlugin.component
      - name: Check Component is in Correct Directory
        run: |
          ls ~/Library/Audio/Plug-Ins/Components/
          ls ~/Library/Audio/Plug-Ins/Components/ExamplePlugin.component/
      - name: Run auval
        run: auval -t aufx Manu Test
